version: '3.8'

services:
  jekyll:
    build: .
    container_name: jekyll-dev
    ports:
      - "4000:4000"   # Jekyll server
      - "35729:35729" # LiveReload
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --watch --drafts --incremental
    tty: true
    stdin_open: true

volumes:
  bundle_cache:
